<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TelegramLike.Chats.Domain\TelegramLike.Chats.Domain.csproj" />
    <ProjectReference Include="..\..\..\TelegramLike.Contracts\TelegramLike.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="TelegramLike.Chats.Domain" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.10.0" />
    <PackageReference Include="MassTransit" Version="8.3.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
